### ISSUE TITLE
'TicTacToeEnv' object has no attribute '_seed'

### ISSUE THREAD

**Issue by istandleet** [haje01/gym-tictactoe#3]
After running set up, I get:

```
>python td_agent.py play -f best_td_agent.dat
Traceback (most recent call last):
  File "td_agent.py", line 590, in <module>
    cli()
  File "D:\anaconda\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\anaconda\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "td_agent.py", line 280, in play
    _play(load_file, HumanAgent('O'), show_number)
  File "td_agent.py", line 296, in _play
    env = TicTacToeEnv(show_number=show_number)
  File "d:\git\soda-cosmos\gym\gym-tictactoe\gym_tictactoe\env.py", line 96, in __init__
    self._seed()
AttributeError: 'TicTacToeEnv' object has no attribute '_seed'
```

**Comment by haje01** [comment]
Fixed with 472d2b76f5c22cb010c74b8105f925d21a7a515a
Thank you for the report.
